name: scheduled-publish
# on:
#   schedule:
#     - cron:  '5 * * * *' # every 5 minutes
on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  publish-latest-content:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # - name: Get submodule content
    #   run: git submodule update --init --recursive

    - name: Go to public submodule
      run: cd $GITHUB_WORKSPACE/public

    - name: Checkout main branch in public submodule
      uses: actions/checkout@v3
      with:
        ref: main
      
    - name: Go to repo root
      run: cd $GITHUB_WORKSPACE

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.91.2'

    - name: Build site with Hugo
      run: hugo -D

    - name: Commit public submodule changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        cd $GITHUB_WORKSPACE/public
        git add .
        git commit -m "[GitHub Actions] Updated site"
        git push