name: scheduled-publish
# on:
#   schedule:
#     - cron:  '5 * * * *' # every 5 minutes
on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  publish-latest-content:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: main

    # - name: Get submodule content
    #   run: git submodule update --init --recursive

    - name: Checkout main branch in public submodule
      # uses: actions/checkout@v3
      # with:
      #   repository: ecriv-ai/ecriv-ai.github.io
      #   path: public
      #   ref: main
      run: |
        cd $GITHUB_WORKSPACE/public
        git status
        cd $GITHUB_WORKSPACE

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.91.2'
        # extended: true

    - name: Build site with Hugo
      run: hugo -D

    - name: Commit public submodule changes
      run: |
        cd $GITHUB_WORKSPACE/public
        git add .
        git commit -m "[GitHub Actions] Updated site"
        git push