name: scheduled-publish
# on:
#   schedule:
#     - cron:  '5 * * * *' # every 5 minutes
on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  publish-latest-content:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo's default branch
      uses: actions/checkout@v3

    - name: Get submodule content
      run: git submodule update --init --recursive

    - name: Checkout main branch in public submodule
      run: |
        cd ./public
        git checkout main
        cd $GITHUB_WORKSPACE

    # - name: Setup Hugo
    #   uses: peaceiris/actions-hugo@v2
    #   with:
    #     hugo-version: '0.91.2'
    #     # extended: true

    # - name: Build site with Hugo
    #   run: hugo -D

    # - name: Commit public submodule changes
    #   run: |
    #     cd public
    #     git add .
    #     git commit -m "[GitHub Actions] Updated site"
    #     git push